export const ADD_NEWPOST = 'ADD_NEWPOST'
export const GET_POSTS = 'GET_POSTS'
export const GET_POSTS_BY_ID = 'GET_POSTS_BY_ID'
export const GET_COMMENTS_BY_ID = 'GET_COMMENTS_BY_ID'
export const EDIT_POST = 'EDIT_POST'
export const DELETE_POST = 'DELETE_POST'
